#!/bin/bash

#Check if all arguments are provided
if [ "$#" -ne 3 ]; then
    echo "Error: Three arguments required."
    echo "Usage: ./add_iso_to_pxe_struct.sh <ARG1 = FULL ISO NAME AND LOCATION> <ARG2 = NAME FOR NEW NFS FOLDER> <ARG3=initrd file compression eg .gz, .lz, etc.>"
    echo "Please provide all three arguments and try again."
    exit 1
fi

#Assign Arg Variables
arg1=$1
arg2=$2
arg3=$3

#--------------------------------------------------------------------------------------------------------------------
#Echo variables
#For internal reference: 
#--------------------------------------------------------------------------------------------------------------------
#arg1 = Full ISO name and location; e.g. - '/media/pxe/21DE-F65T/pxe_192.7.1.iso'
#ARG 1 is usually best called from the direct folder to avoid complicated tree structures.
#--------------------------------------------------------------------------------------------------------------------
#arg2 = Name for new nfs folder. To stick with current naming schema it should be: pxe_<version_number>; e.g. - 'pxe_192.7.1'
#I recommend sticking with this schema as it makes changing out the grub.cfg very easy until I add that logic
#--------------------------------------------------------------------------------------------------------------------
#arg3 = File compression type. For mint 22 this is always '.gz' - This DOES change for other operating system types.
#Yes, you do need the '.' in front of '.lz', '.gz', '.etc'.
#--------------------------------------------------------------------------------------------------------------------
echo "First Argument: $arg1"
echo "Second Argument: $arg2"
echo "Third Argument: $arg3"
#--------------------------------------------------------------------------------------------------------------------

#Mount ISO with ARG1
sudo mount -o loop -t iso9660 $arg1 /mnt

#Create folder and transfer files to folder made with ARG2
sudo rsync -av --progress /mnt/ /var/www/html/$arg2
sudo mkdir -p /tftp/boot/$arg2

#Establish the initrd and vmlinuz files using args 2 and 3
#BE AWARE THIS WILL FAIL IF THE initrd is NOT named initrd<.extension>
sudo rsync -av /var/www/html/$arg2/casper/initrd$arg3 /tftp/boot/$arg2/initrd$arg3
sudo rsync -av /var/www/html/$arg2/casper/vmlinuz /tftp/boot/$arg2/vmlinuz

#Unmount the mounted iso
sudo umount /mnt

#Change all ownership to nobody:nogroup and rights to 777
sudo /home/pxe/Desktop/Usr_Bash/CHOWN-CHMOD

#Restart all PxE Hosting services
sudo /home/pxe/Desktop/Usr_Bash/Reset_PxE
