#!/bin/bash

#Change Ownership of /tftp/* and /var/www/html/*
#This is to make PxE Accessible to ANY incoming request.
sudo chown nobody:nogroup -R /tftp/*
sudo chown nobody:nogroup -R /var/www/html/*

#Make the same folders fully read, write, and execute friendly.
sudo chmod 777 -R /tftp/*
sudo chmod 777 -R /var/www/html/*
